// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
)
RETURNING id, created_at, updated_at, email
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const existUser = `-- name: ExistUser :one

SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) ExistUser(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existUser, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const wipeUsers = `-- name: WipeUsers :exec
DELETE FROM users
`

func (q *Queries) WipeUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, wipeUsers)
	return err
}
